export {
  formatNatTableUiNumber,
  mergeColumnVisibilityLabels,
  mergeHeaderActionLabels,
  mergeNatTableUiIntl,
  mergePageSizeLabels,
  mergePagerLabels,
  mergeScrollControlLabels,
  mergeSelectionLabels,
  NAT_TABLE_UI_DEFAULT_INTL,
  NAT_TABLE_UI_ENGLISH_INTL,
  NAT_TABLE_UI_ENGLISH_LOCALE,
  NAT_TABLE_UI_INTL,
  provideNatTableUiIntl,
  resolveNatTableUiIntl,
} from 'ng-advanced-table-locales';

export type {
  NatTableColumnVisibilityIntl,
  NatTableHeaderActionsIntl,
  NatTablePageSizeIntl,
  NatTablePagerIntl,
  NatTableScrollControlIntl,
  NatTableSearchIntl,
  NatTableSelectionIntl,
  NatTableToolbarIntl,
  NatTableUiIntl,
  NatTableUiIntlConfig,
  NatTableUiIntlProviderConfig,
  NatTableUiNumberFormatter,
} from 'ng-advanced-table-locales';
